# Generated by Django 5.1.7 on 2025-03-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_resgister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('status', models.CharField(default='user', max_length=20)),
                ('Buildingname', models.CharField(max_length=30, null=True)),
                ('housenumber', models.CharField(max_length=30, null=True)),
                ('landmark', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('pincode', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
