# Generated by Django 5.1.7 on 2025-04-16 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='myorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(max_length=20)),
                ('payment_amount', models.IntegerField(max_length=20)),
                ('order_ID', models.IntegerField(unique=True)),
                ('order_date', models.DateTimeField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user_resgister')),
            ],
        ),
    ]
