# Generated by Django 5.1.7 on 2025-04-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='order_ID',
        ),
    ]
