# Generated by Django 5.1.7 on 2025-04-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_myorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
