# Generated by Django 5.1.7 on 2025-04-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='messegebox',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myorder',
            name='payment_amount',
            field=models.IntegerField(),
        ),
    ]
