# Generated by Django 5.1.7 on 2025-04-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_contacts_messegebox_alter_myorder_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='messegebox',
            new_name='messagebox',
        ),
    ]
